### ISSUE TITLE
Investigate replacing products.json with a real database

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#1603] opened 2023-03-20 14:29 UTC
### Describe request or inquiry
* Today, the list of products comes from a JSON file. See [products.json](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/src/productcatalogservice/products.json).
* In reality, such a list of products would be stores in a database (e.g., Postgres).
* This GitHub issue is purely for evaluating _if and how_ Online Boutique would support this feature.
* Ideally, we would:
    * find out what databases are common amongst GCP users from the retail vertical
    * consider adding this feature as a Kustomize Component
    * consider using this feature for Online Boutique's default deployment
    * evaluate the value this would actually create. For instance, we support different database integrations through the `cartservice`. Is it worth complicating Online Boutique by adding "statefulness" to another microservice. What additional technical lessons would such a feature convey?

### What purpose/environment will this feature serve? 
* This is part of a recent effort to make Online Boutique relate more to the ecommerce and retail industry.
* This issue was inspired by [this Google-internal comment](https://docs.google.com/document/d/1z3vBmlQfUEAaCBO2LpFgMGEggNqboSp83eLiKufD7g4/edit?disco=AAAAsnQ_qyQ).

**Comment by NimJay** [comment] 2023-09-12 12:57
Update to cool down team out-of-SLO: this issue is still low priority.

**Comment by bourgeoisor** [comment] 2024-04-17 21:28
This seems like a duplicate of https://github.com/GoogleCloudPlatform/microservices-demo/issues/1260

Closing.

**Closed by bourgeoisor** 2024-04-17 21:28 UTC
Labels: type: feature request, priority: p3
