### ISSUE TITLE
improvement: fix the cloud debugger errors in nodejs services

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/microservices-demo#645] opened 2021-11-29 22:04 UTC
### Describe the bug 
- There are several `insufficient scopes` authentication errors in the logs for the **_nodejs services_** in the CI clusters (`onlineboutique-pr` and `onlineboutique-master`)
- This is because that the `Cloud Debugger API` is not accessible from these clusters as these clusters were not created with the necessary access scopes.
- Thus, the nodes that make up these clusters don't have access to the `Cloud Debugger API` 

### To Reproduce 
- Create a PR on this repo or you can use an existing PR
- Navigate to the PR specific namespace on the CI cluster `onlineboutique-pr`
- Open up one of the two nodejs services `currencyservice` or `paymentsservice` and view the logs
- Filter logs by `ERROR` logs

### Logs  & Screenshots 
![image](https://user-images.githubusercontent.com/7249208/143894574-6cdb3b5d-0aa7-4674-92d1-1fcd613517ef.png)

### Environment 
- Existing CI clusters for this repo

### Additional context 
- This was discovered when debugging the memory leak issue #538 

### Solution ideas:
- There were multiple thoughts around handling this 
    - _i.e. whether we should disable debugger by default and have is disabled in the CI clusters as well_
    - _[see chat for more details](https://chat.google.com/room/AAAAtbr2o0E/ncs4aXhontw)_
- I suggest we have the debugger switched on in the CI clusters so that it enables us to debug and experiment a full feature set on the applications whenever a change is made. 
- We can do this by creating the clusters with the **`--scopes=https://www.googleapis.com/auth/cloud_debugger,gke-default`** scopes and updating the CI yamls to point to the new cluster, then decommissioning the old CI clusters. I have [a PR](https://github.com/GoogleCloudPlatform/microservices-demo/pull/644) that achieves this.

- But there may be extra work that needs to be done according to what the team decides.
  - If the team decides that we want to disable `debugger` by default on the sample then we might have to modify some of the yamls and ensure that it is only enabled for the CI clusters.
  - We need to have a discussion around whether this will create confusion for external stakeholders, and how we can have parity between the [`release yamls`](https://github.com/GoogleCloudPlatform/microservices-demo/tree/master/release) and the [`dev yamls`](https://github.com/GoogleCloudPlatform/microservices-demo/tree/master/kubernetes-manifests).

- So I have left the PR closed for someone who picks this issue to have a starting point (if they want to use it)

### Exposure 
- Internal/Local

**Comment by Shabirmean** [comment] 2022-06-16 16:58
This issue might not be relavant with the Cloud Debugger sunset being announced as explained in #836

**Comment by mathieu-benoit** [comment] 2022-08-31 13:41
Closing this issue now, since:
- Since https://github.com/GoogleCloudPlatform/microservices-demo/releases/tag/v0.3.5, we turned off by default this Logging/Debugging environment variables
- The use of Google Cloud Debugger will be deprecated as per https://github.com/GoogleCloudPlatform/microservices-demo/issues/836

In the meantime, if the issue is faced, the proper values for the `--scopes` parameter when creating the GKE cluster is required, see description of this issue.

**Closed by mathieu-benoit** 2022-08-31 13:41 UTC
Labels: type: bug, type: cleanup, priority: p3
