### ISSUE TITLE
failed to build productcatalogservice locally

### ISSUE THREAD

**Issue by eshen1991** [GoogleCloudPlatform/microservices-demo#497] opened 2021-01-28 22:19 UTC
Tried to build the docker image locally for productcatalogservice and got the following error:

➜  productcatalogservice git:(master) docker build -t catalog . 
Sending build context to Docker daemon  131.1kB
Step 1/15 : FROM golang:1.15-alpine AS builder
1.15-alpine: Pulling from library/golang
...
...
Step 10/15 : RUN GRPC_HEALTH_PROBE_VERSION=v0.3.6 &&     wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 &&     chmod +x /bin/grpc_health_probe
 ---> Running in dcbf47ad63fe
**wget: bad address 'github.com'**
The command '/bin/sh -c GRPC_HEALTH_PROBE_VERSION=v0.3.6 &&     wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 &&     chmod +x /bin/grpc_health_probe' returned a non-zero code: 1

**Comment by askmeegs** [comment] 2021-02-02 15:07
Hi Eric, sorry you're seeing this! I was unable to reproduce this locally, `Step 10` ran ok on the latest master branch - 

```
Step 10/15 : RUN GRPC_HEALTH_PROBE_VERSION=v0.3.6 &&     wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 &&     chmod +x /bin/grpc_health_probe
 ---> Running in 6f65ffd843d1
...
Successfully tagged catalog:latest
```

I'm running Docker Desktop on Mac - 
```
❯ docker -v
Docker version 20.10.2, build 2291f61
``` 

Although I wouldn't think Docker itself would be causing that wget issue. Is it possible you briefly lost network connectivity during the build? ([This `wget bad address` issue](https://github.com/brikis98/docker-osx-dev/issues/91) referenced that).

**Comment by mathieu-benoit** [comment] 2021-02-12 17:57
Same here, it's working fine for me locally, in Cloud Shell and even in the CI of this repo (new version just released without any issue). Closing this one for now, but @eshen1991, please feel free to reopen that issue if you still have it.

**Closed by mathieu-benoit** 2021-02-12 17:57 UTC

**Comment by braxtonj** [comment] 2021-03-08 08:18
I am experiencing the same issue building for a GCP cluster.

```
This repo
  master branch
  commit 3a1850d65f8ca9dfd361f741791c9b7506226827

Docker version 20.10.0, build 7287ab3

Google Cloud SDK 330.0.0
  bq 2.0.65
  core 2021.02.26
  gsutil 4.59

skaffold version v1.20.0

kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.12-gke.1210", GitCommit:"199a41188dc0ca5d6d95b1cc7e8ba96e05f9dd0a", GitTreeState:"clean", BuildDate:"2021-02-05T18:03:16Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**The error**
```
Building [productcatalogservice]...
Sending build context to Docker daemon  129.5kB
Step 1/15 : FROM golang:1.15-alpine AS builder
 ---> b250ad1c7bff
Step 2/15 : RUN apk add --no-cache ca-certificates git
 ---> Using cache
 ---> 304096fadf55
Step 3/15 : WORKDIR /src
 ---> Using cache
 ---> 399e8ca8e32d
Step 4/15 : COPY go.mod go.sum ./
 ---> d65bf821fd57
Step 5/15 : RUN go mod download
 ---> Running in d9611ed7ac9b
 ---> 3afc15874d67
Step 6/15 : COPY . .
 ---> 8da37ea7c14e
Step 7/15 : RUN go build -o /productcatalogservice .
 ---> Running in 5ade0dc34f26
 ---> f3ef16b923a7
Step 8/15 : FROM alpine AS release
 ---> 28f6e2705743
Step 9/15 : RUN apk add --no-cache ca-certificates
 ---> Using cache
 ---> 7b459212e939
Step 10/15 : RUN GRPC_HEALTH_PROBE_VERSION=v0.3.6 &&     wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 &&     chmod +x /bin/grpc_health_probe
 ---> Running in f9a1a5e00a63
wget: bad address 'github-releases.githubusercontent.com'
Building [paymentservice]...
Building [recommendationservice]...
Building [shippingservice]...
Building [checkoutservice]...
Building [cartservice]...
Building [currencyservice]...
Building [emailservice]...
Building [frontend]...
Building [loadgenerator]...
failed to build: unable to stream build output: The command '/bin/sh -c GRPC_HEALTH_PROBE_VERSION=v0.3.6 &&     wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 &&     chmod +x /bin/grpc_health_probe' returned a non-zero code: 1. Please fix the Dockerfile and try again..
```
