### ISSUE TITLE
Layer 7 loadbalancing using Cilium Envoy

### ISSUE THREAD

**Issue by philippmoritzer** [GoogleCloudPlatform/microservices-demo#1850] opened 2023-06-19 20:46 UTC
I'm trying to get the microservices-demo to work using the layer 7 loadbalancing feature provided by cilium. I enabled tracing in the microservices-demo and made no further changes. This is my cilium deployment:

```
kubeProxyReplacement: strict

l7Proxy: true
extraConfig:
 enable-envoy-config: "true"
loadBalancer:
  l7:
    backend: envoy
```
The services (every single one except for loadgenerator) are then annotated with
```
annotations:
    service.cilium.io/lb-l7: enabled
```

see: https://docs.cilium.io/en/stable/network/servicemesh/envoy-load-balancing/

which creates an envoy config. That works, and when accessing the GRPC Services by itself it works and the requests go through the envoy proxy, which is observable by using Prometheus. But when using the frontend or the loadgenerator tool, I get following error (grpc error descriptions vary):

```
rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 110
could not retrieve currencies
main.(*frontendServer).homeHandler
	/src/handlers.go:59
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2122
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210
main.(*logHandler).ServeHTTP
	/src/middleware.go:82
main.ensureSessionID.func1
	/src/middleware.go:109
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2122
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
	/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.40.0/handler.go:213
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1995
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1598
```

It works for the demo application, but not for the microservices-demo project. I don't quiet understand what I'm missing here, what's different for microservices-demo for it not to work?

**Comment by NimJay** [comment] 2023-06-20 20:46
**Heads-up:** Since this question is specific to Cilium and its features (and since this repo is catered towards showcasing raw Kubernetes and GKE), we won't be able to provide a lot of support here. Sorry!

Judging from the error message:
```
rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 110
could not retrieve currencies
```
it looks like the `frontend` service isn't able to reach the 
[Relevant code here](https://github.com/GoogleCloudPlatform/microservices-demo/blob/315831a0fefcbad1ce05c4c4ccadb30046010402/src/frontend/handlers.go#L60).
Question:
**1.** Could you double-check (e.g., `kubectl get pods`) that the currencyservice is running?
**2.** Was Online Boutique working _before_ you enabled the ["Proxy Load Balancing for Kubernetes Services (beta)" feature](https://docs.cilium.io/en/stable/network/servicemesh/envoy-load-balancing/)?

Consider asking a question in the [cillium GitHub repo](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Akind%2Fquestion+).

**Comment by philippmoritzer** [comment] 2023-06-22 19:09
Thank you, it worked previously, yes. It also works well with istio. Every service is running and accessible. They are just not accessible using the Frontend service or service to service communication. I asked in the cilium GitHub in parallel now, thank you for the heads up. For a long time I had a feeling it was about how the microservices-demo handles grpc communication, but it‘s probably linked to the envoy configuration provided by cilium service mesh.

**Comment by bourgeoisor** [comment] 2024-04-17 21:23
Closing this since Cilium is not something that Online Boutique officially supports. If you believe the issue is in the core Online Boutique experience and unrelated to Cilium, feel free to reopen!

**Closed by bourgeoisor** 2024-04-17 21:23 UTC
Labels: type: bug, priority: p3
