### ISSUE TITLE
EKS: rpc error: code = Unavailable desc = connection error: desc = transport: Error while dialing: dial tcp: lookup currencyservice

### ISSUE THREAD

**Issue by harmindersinghk** [GoogleCloudPlatform/microservices-demo#2153] opened 2023-09-29 08:52 UTC
I am trying to run the online boutique app using Argocd on EKS. Argocd app is installed ok and all pods are up and running. I have deployed everything in argocd namespace itself for now.

<img width="936" alt="Screenshot 2023-09-29 at 09 45 43" src="https://github.com/GoogleCloudPlatform/microservices-demo/assets/37942739/3a74c160-b103-40df-8971-5a90662b0850">

Frontend-external service of type load balancer is created ok and a loadbalancer is assigned to service.

<img width="812" alt="Screenshot 2023-09-29 at 09 47 06" src="https://github.com/GoogleCloudPlatform/microservices-demo/assets/37942739/2b247e78-03f4-4dab-add9-df5f8d7f512d">

When I try to access the application in browser using the loadbalancer url. I see following:

<img width="1189" alt="Screenshot 2023-09-29 at 09 48 49" src="https://github.com/GoogleCloudPlatform/microservices-demo/assets/37942739/aef4b01a-392d-4c92-b498-b8f9b8467fbd">

I see following in the frontend pod logs:

```
{
  "error": "could not retrieve currencies: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: lookup currencyservice on 172.20.0.10:53: read udp 10.0.6.19:57531->172.20.0.10:53: i/o timeout\"",
  "http.req.id": "29da66df-2c44-4e5b-85ee-1cc9bd987c48",
  "http.req.method": "GET",
  "http.req.path": "/",
  "message": "request error",
  "session": "60f546b2-0d19-4fab-ba6c-d94b304c4f97",
  "severity": "error",
  "timestamp": "2023-09-29T08:49:59.989348388Z"
}
{
  "http.req.id": "29da66df-2c44-4e5b-85ee-1cc9bd987c48",
  "http.req.method": "GET",
  "http.req.path": "/",
  "http.resp.bytes": 4626,
  "http.resp.status": 500,
  "http.resp.took_ms": 2,
  "message": "request complete",
  "session": "60f546b2-0d19-4fab-ba6c-d94b304c4f97",
  "severity": "debug",
  "timestamp": "2023-09-29T08:49:59.991394372Z"
}
```

Any ideas would be greatly appreciated. I couldn't find any example of this being installed on EKS.

**Comment by bourgeoisor** [comment] 2023-09-29 21:23
It looks like the frontend error is that it (the frontend) can't communicate with the currencyservice. Could you check if that service has any interesting logs, perhaps?

**Comment by harmindersinghk** [comment] 2023-09-30 21:49
Thanks for your response. For some reason the pod networking (coredns, kube-proxy) is not working intermittently. I restarted everything and it worked. I am trying to debug the networking issue now.

**Comment by bourgeoisor** [comment] 2023-10-02 15:03
Let me know if you find anything. There's a possibility this is an issue on EKS' side, but I only have limited capabilities to diagnose such issues unfortunately

**Comment by bourgeoisor** [comment] 2024-01-29 17:25
@suddencoffee can you paste the output of `kubectl top nodes`?

**Comment by bourgeoisor** [comment] 2024-01-29 20:48
cc: @NimJay have you ever encountered something like this?

**Comment by bourgeoisor** [comment] 2024-01-30 16:20
So to clarify, for you it works fine on Linux with Minikube, but not macOS with Minikube?

**Comment by bourgeoisor** [comment] 2024-01-31 19:23
I wonder if it's an Arm thing. @NimJay remind me, does Online Boutique support Arm officially?

**Comment by NimJay** [comment] 2024-01-31 20:26
No, unfortunately, Online Boutique doesn't support ARM.
@suddencoffee If you're confident that it's an ARM issue, you may be able to make some tweaks to various Dockerfiles, etc. to get Online Boutique working for ARM.
Relevant thread: https://github.com/GoogleCloudPlatform/microservices-demo/issues/622

**Comment by bourgeoisor** [comment] 2024-04-17 22:12
Closing as a duplicate of https://github.com/GoogleCloudPlatform/microservices-demo/issues/622

**Closed by bourgeoisor** 2024-04-17 22:12 UTC
Labels: type: bug, priority: p3
