### ISSUE TITLE
Adservice gets connection reset by peer

### ISSUE THREAD

**Issue by jessberg** [GoogleCloudPlatform/microservices-demo#559] opened 2021-06-14 14:52 UTC
I am running the demo on GCP with Istio installed, and I'm using my own load generator that has 1500 users instead of the current load generator's 10.  After roughly 3 minutes of running, I stop getting regular responses and only get 503:  Service Unavailable.  I looked in the logs and it seems like it is due to an error in Adservice.  The logs for Adservice repeatedly say 
```
INFO: Transport failed
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
GRPC: src/core/lib/security/credentials/oauth2/oauth2_credentials.cc:154 Call to http server ended with error 426 [].
Jun 14, 2021 2:22:43 PM io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport notifyTerminated
```
I believe the 426 is saying that something should be upgraded, but I'm not quite sure what.  Any help would be appreciated.

**Comment by mathieu-benoit** [comment] 2021-06-14 16:13
I'm also getting this error with `adservice`:
```
onlineboutique                    adservice-dbfd5646f-l5dxc                                   1/2     CrashLoopBackOff   2421       6d1h
```
```
E0614 15:55:26.452806    22 throttler_api.cc:86] GRPC: src/core/lib/security/credentials/oauth2/oauth2_credentials.cc:154 Call to http server ended with error 426 [].
```

More information about my setup in case that could help:
- GKE 1.20
- Workload Identity enabled
- I'm also deploying this service with both `DISABLE_STATS` and `DISABLE_TRACING` set to `1` as value

**Comment by jessberg** [comment] 2021-06-16 13:16
Yes, I'm deploying with GKE 1.20 as well.  I also run istio with the command
```
istioctl install --set profile=demo --set meshConfig.enableTracing=True
```
I am deploying with DISABLE_STATS and DISABLE_TRACING commented out.  Is there any other information that would be useful about my setup?

**Comment by Shabirmean** [comment] 2021-06-28 03:58
Hi @jessberg,

I see that the loadgenerator tests mainly fail on **productcatalogservice** and the **cartservice**.  I also noticed the following logs in the **productcatalogservice**:
```
OpenCensus Stackdriver exporter: failed to upload 709 spans: buffer full
```

It looks like that the tracing library is struggling to handle the load. Can you try disabling tracing? You can do this by **uncommenting** _(uncommented means disabled)_ the following setting in the manifests **DISABLE_TRACING**. Try disabling it for all the services. I am able to disable tracing and have the _loadgenerator_ run tests for _~1500 users_ without failures.

If you'd like to keep tracing enabled then you can also try setting the following options on the tracer as per [this troubleshooting guide](https://cloud.google.com/trace/docs/setup/go#oc-upload-fail):
```go
stackdriver.NewExporter(stackdriver.Options{
    TraceSpansBufferMaxBytes: 64,
    BundleDelayThreshold: time.Duration(100) * time.Millisecond,
    BundleCountThreshold: 1,
})
```

Let us know if this resolves the issue of _loadgenerator_ failing.

**Comment by jessberg** [comment] 2021-06-29 00:19
Oh, that does make sense.  I disabled tracing by uncommenting the lines in the release/kubernetes_manifest.yaml file on every deployment.  There is no connection reset by peer error, but I still have the following error on adservice
```
GRPC: src/core/lib/security/credentials/oauth2/oauth2_credentials.cc:154 Call to http server ended with error 426
```
It looks like I also have another type of error now.  On adservice I've got 
```
WARNING: ApiException thrown when exporting TimeSeries
```
followed by
```
com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: One or more TimeSeries could not be written: The set of resource labels is incomplete. 
Missing labels: (location).: timeSeries[0-2] at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49) at 
com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72) at 
com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60) at 
com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) at 
com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) at 
com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1050) at 
com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) at 
com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1176) at 
com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969) at 
com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:760) at 
io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563) at 
io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533) at 
io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:413) at 
io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) at 
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) at 
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:721) at 
io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) at 
io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) at 
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at 
java.util.concurrent.FutureTask.run(FutureTask.java:266) at 
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:18
0) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
 Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed at 
com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57) at 
com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) at 
com.google.cloud.monitoring.v3.MetricServiceClient.createTimeSeries(MetricServiceClient.java:1156) at 
io.opencensus.exporter.stats.stackdriver.CreateTimeSeriesExporter.export(CreateTimeSeriesExporter.java:85) at 
io.opencensus.exporter.stats.stackdriver.CreateMetricDescriptorExporter.export(CreateMetricDescriptorExporter.java:157) at
 io.opencensus.exporter.metrics.util.MetricReader.readAndExport(MetricReader.java:167) at 
io.opencensus.exporter.metrics.util.IntervalMetricReader$Worker.readAndExport(IntervalMetricReader.java:177) at 
io.opencensus.exporter.metrics.util.IntervalMetricReader$Worker.run(IntervalMetricReader.java:170) ... 1 more 
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: One or more TimeSeries could not be written: The set of resource labels is incomplete. Missing labels: (location).: timeSeries[0-2] at 
io.grpc.Status.asRuntimeException(Status.java:533) ... 14 more

```

**Comment by mathieu-benoit** [comment] 2021-11-24 19:16
Maybe not related but JFYI, I found out what I was doing wrong about my issue mentioned earlier in this thread https://github.com/GoogleCloudPlatform/microservices-demo/issues/559#issuecomment-860810436. I actually set too low the values of the `resources`.`requests`/`limits` which landed to kill my `adservice` pod. When I set those values back to what it's recommended in there https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/release/kubernetes-manifests.yaml#L713, I fixed the issue I caused by myself.
So JFYI @jessberg in case you have also your `adservice` taking too much memory/cpu and being killed with your load tests?

**Comment by askmeegs** [comment] 2021-12-30 16:16
Closing this issue as possibly a non-Istio related bug, that instead may be related to insufficient resource requests + limits for the services. @jessberg  please reopen if you adjust your resource requests and you're still seeing this problem. Thanks!

**Closed by askmeegs** 2021-12-30 16:16 UTC
Labels: type: bug, priority: p2, lang: java
