### ISSUE TITLE
HTTP 500 Internal Server Error - RPC error - currencyservice

### ISSUE THREAD

**Issue by scomri** [GoogleCloudPlatform/microservices-demo#962] opened 2022-08-21 15:37 UTC
I am fairly new to Kubernetes, therefore having a hard time understanding what is exactly the error and how to resolve it.
Thanks in advance!

### Describe the bug 
![image](https://user-images.githubusercontent.com/93886291/185795239-590f60f6-5276-485a-aa71-e9fe747b70a1.png)

### To Reproduce 

Simply cloned the repository and ran: `kubectl apply -f ./release/kubernetes-manifests.yaml`
Then tried to open the frontend page in browser, and the above error shows.

The scripts I'm using to construct my cluster's nodes (master & worker): (after that I'm joining them)

Master:
```
#! /bin/bash

sudo apt-get update -y
sudo swapoff -a
sudo modprobe br_netfilter
sudo echo "net.bridge.bridge-nf-call-iptables = 1" | sudo tee -a /etc/sysctl.conf
sudo echo "1" | sudo tee -a /proc/sys/net/ipv4/ip_forward
sudo sysctl -p /etc/sysctl.conf
kube
sudo apt update -y && sudo apt upgrade -y

OS=xUbuntu_20.04
CRIO_VERSION=1.23
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /"|sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$CRIO_VERSION/$OS/ /"|sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$CRIO_VERSION.list

curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$CRIO_VERSION/$OS/Release.key | sudo apt-key add -
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | sudo apt-key add -


sudo apt update -y
sudo apt install cri-o cri-o-runc -y


sudo systemctl enable crio.service
sudo systemctl start crio.service


sudo apt install cri-tools


sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl

sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl
sudo systemctl restart crio
sudo kubeadm init --cri-socket unix:///var/run/crio/crio.sock
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
kubectl get cs
kubectl cluster-info
kubectl get pods -n kube-system

mv $HOME/.kube $HOME/.kube.bak
mkdir $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
sudo systemctl restart crio
sudo service kubelet restart
```

Workers:
```
#! /bin/bash

sudo apt-get update -y
sudo swapoff -a
sudo modprobe br_netfilter
sudo echo "net.bridge.bridge-nf-call-iptables = 1" | sudo tee -a /etc/sysctl.conf
sudo echo "1" | sudo tee -a /proc/sys/net/ipv4/ip_forward
sudo sysctl -p /etc/sysctl.conf
kube
sudo apt update -y && sudo apt upgrade -y

OS=xUbuntu_20.04
CRIO_VERSION=1.23
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /"|sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$CRIO_VERSION/$OS/ /"|sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$CRIO_VERSION.list

curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$CRIO_VERSION/$OS/Release.key | sudo apt-key add -
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | sudo apt-key add -


sudo apt update -y
sudo apt install cri-o cri-o-runc -y


sudo systemctl enable crio.service
sudo systemctl start crio.service


sudo apt install cri-tools


sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl

sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl
sudo systemctl restart crio
```

### Logs  
currencyservice pod logs:

```
Name:         currencyservice-694d677bfb-k9kcc
Namespace:    default
Priority:     0
Node:         ip-172-31-3-139/172.31.3.139
Start Time:   Sun, 21 Aug 2022 13:44:38 +0000
Labels:       app=currencyservice
              pod-template-hash=694d677bfb
Annotations:  cni.projectcalico.org/containerID: b62b65134833f0f32c530f0768124ad5075fecdff4bf05d114cdf4fe77560e2b
              cni.projectcalico.org/podIP: 172.16.110.156/32
              cni.projectcalico.org/podIPs: 172.16.110.156/32
Status:       Running
IP:           172.16.110.156
IPs:
  IP:           172.16.110.156
Controlled By:  ReplicaSet/currencyservice-694d677bfb
Containers:
  server:
    Container ID:   cri-o://53af05e04b7ccc0657d8dc461c9cc938dcfbcac1ebab59c5614ec22f36118217
    Image:          gcr.io/google-samples/microservices-demo/currencyservice:v0.3.9
    Image ID:       gcr.io/google-samples/microservices-demo/currencyservice@sha256:c52b683e393b43fc12ffa3d356b7f9b8aec68805e7cb1b09e689450e1a0d7159
    Port:           7000/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Sun, 21 Aug 2022 13:44:39 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  128Mi
    Requests:
      cpu:      100m
      memory:   64Mi
    Liveness:   exec [/bin/grpc_health_probe -addr=:7000] delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [/bin/grpc_health_probe -addr=:7000] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      PORT:              7000
      DISABLE_TRACING:   1
      DISABLE_PROFILER:  1
      DISABLE_DEBUGGER:  1
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-6fcvj (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kube-api-access-6fcvj:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  26s   default-scheduler  Successfully assigned default/currencyservice-694d677bfb-k9kcc to ip-172-31-3-139
  Normal   Pulled     25s   kubelet            Container image "gcr.io/google-samples/microservices-demo/currencyservice:v0.3.9" already present on machine
  Normal   Created    25s   kubelet            Created container server
  Normal   Started    25s   kubelet            Started container server
  Warning  Unhealthy  23s   kubelet            Readiness probe failed: timeout: failed to connect service ":7000" within 1s
```

### Environment 
- AWS EC2 instances, all with the same specs: Ubuntu 20.04, 4 CPU, 16GB memory,  100GB storage memory
- I built the cluster with kubeadm, using CRI-O engine.

### Exposure 
Deploying the application on my local machine with minikube seems to work just fine, which means the problem is probably in my k8s cluster.

**Comment by NimJay** [comment] 2022-08-25 18:52
Hi @scomri,

Thanks for creating such a clear (detailed) issue! :)

1. If you suspect that the issue is your environment, I suggest trying to deploy an app simpler than Online Boutique. Try deploying [this "Hello, world!" app](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/main/hello-app). You will need to deploy this [Deployment](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/hello-app/manifests/helloweb-deployment.yaml) and this [Service](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/hello-app/manifests/helloweb-service-load-balancer.yaml) using `kubectl apply -f <path-to-file>`. The Service is of type `LoadBalancer` so it will get an external IP address assigned to it which you can check using `kubectl get service`.
2. How are all the Pods and Services doing? What's the output of `kubectl get pods` and `kubectl get services`?
3. Is there a reason you're not using a managed Kubernetes service like [Google Kubernetes Engine](https://cloud.google.com/kubernetes-engine/docs/deploy-app-cluster)? You're less likely to run into environment-related issues if you use a managed service.

Hope my thoughts above help. 🤞 
Good luck!

**Comment by scomri** [comment] 2022-08-28 09:28
In the end I managed to deploy the application successfully using Istio mesh. Thank you anyways for your comment!!

**Comment by NimJay** [comment] 2022-08-29 11:03
Happy to hear that! :)
I'll close this issue then.

**Comment by scomri** [comment] 2022-10-20 09:45
Hi @NimJay 

Nowadays I'm trying to deploy the app without Istio. Is there a way to solve the initial error?

Adding the pods and services states in the cluster:

**kubectl get pods**
NAME                                     READY   STATUS    RESTARTS   AGE
adservice-7dc899d57f-9qpdk               1/1     Running   0          150m
cartservice-6dbfb7f57-2bdld              1/1     Running   0          150m
checkoutservice-659797fc89-ms4hk         1/1     Running   0          150m
currencyservice-86f55694b9-hxkwf         1/1     Running   0          150m
emailservice-7d677b875-tjpvr             1/1     Running   0          150m
frontend-bd5876b7f-l48mq                 1/1     Running   0          150m
loadgenerator-76d87b65fc-qd9xl           1/1     Running   0          150m
paymentservice-7946999b79-qtjmk          1/1     Running   0          150m
productcatalogservice-7465548fcc-n7xzq   1/1     Running   0          150m
recommendationservice-9585d657c-kdf48    1/1     Running   0          150m
redis-cart-7f557cdb55-z6kxk              1/1     Running   0          150m
shippingservice-ff9646559-prr9t          1/1     Running   0          150m

kubectl get svc
NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
adservice               ClusterIP      10.104.136.81    <none>        9555/TCP       157m
cartservice             ClusterIP      10.109.221.59    <none>        7070/TCP       157m
checkoutservice         ClusterIP      10.98.79.170     <none>        5050/TCP       157m
currencyservice         ClusterIP      10.99.137.98     <none>        7000/TCP       157m
emailservice            ClusterIP      10.100.194.62    <none>        5000/TCP       157m
frontend                ClusterIP      10.108.24.111    <none>        80/TCP         157m
frontend-external       LoadBalancer   10.98.180.203    <pending>     80:30264/TCP   157m
kubernetes              ClusterIP      10.96.0.1        <none>        443/TCP        22h
paymentservice          ClusterIP      10.107.225.123   <none>        50051/TCP      157m
productcatalogservice   ClusterIP      10.104.245.140   <none>        3550/TCP       157m
recommendationservice   ClusterIP      10.107.6.202     <none>        8080/TCP       157m
redis-cart              ClusterIP      10.101.48.34     <none>        6379/TCP       157m
shippingservice         ClusterIP      10.102.62.207    <none>        50051/TCP      157m

And to your last question, we want to have Kubernetes manually managed as it is a part of a research we are conducting.

Thanks in advance!


> Hi @scomri,
> 
> Thanks for creating such a clear (detailed) issue! :)
> 
> 1. If you suspect that the issue is your environment, I suggest trying to deploy an app simpler than Online Boutique. Try deploying [this "Hello, world!" app](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/main/hello-app). You will need to deploy this [Deployment](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/hello-app/manifests/helloweb-deployment.yaml) and this [Service](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/hello-app/manifests/helloweb-service-load-balancer.yaml) using `kubectl apply -f <path-to-file>`. The Service is of type `LoadBalancer` so it will get an external IP address assigned to it which you can check using `kubectl get service`.
> 2. How are all the Pods and Services doing? What's the output of `kubectl get pods` and `kubectl get services`?
> 3. Is there a reason you're not using a managed Kubernetes service like [Google Kubernetes Engine](https://cloud.google.com/kubernetes-engine/docs/deploy-app-cluster)? You're less likely to run into environment-related issues if you use a managed service.
> 
> Hope my thoughts above help. 🤞 Good luck!

**Comment by NimJay** [comment] 2022-10-24 12:15
I'm going to reopen this issue so it's visible to the rest of my team.

**Comment by NimJay** [comment] 2022-10-24 12:19
@scomri,

1. Which version of (e.g., are you using a specific `release/vX.Y.Z` branch or tag? are you using a fairly recent commit of the `main` branch)?
2. Are you still receiving the exact same error from your original description in this issue:
In other words, are you seeing the following in your `currencyservice` logs:
```
  Warning  Unhealthy  23s   kubelet            Readiness probe failed: timeout: failed to connect service ":7000" within 1s
```
It's strange because your `kubectl get pods` output suggests that all your Pods are `RUNING` fine.

**Comment by scomri** [comment] 2022-11-16 12:40
I am still not sure what was the problem,
but now I'm using that latest release to this date and everything is working fine.

Seems like the error I posted here in the first time is about some timeout that occurred because of something (that I don't know what it could be).

**Comment by NimJay** [comment] 2022-11-23 15:29
> but now I'm using that latest release to this date and everything is working fine.

Thanks for the update.
I'll close this since "everything is working fine".

**Closed by NimJay** 2022-11-23 15:29 UTC
Labels: type: question, priority: p3
