### ISSUE TITLE
skaffold run Docker build failed in Minikube (Apple Silicon M2)

### ISSUE THREAD

**Issue by shazibulislam** [GoogleCloudPlatform/microservices-demo#1448] opened 2023-01-16 20:23 UTC
### Docker build unable to build in M2 Mac
Docker images are configured to run in linux/amd64 and not for linux/arm64 
### To Reproduce 
After installing Docker desktop and minikube, run ```skaffold run``` and it will show the following error

```
build [shippingservice] failed: exit status 1. Docker build ran into internal error. Please retry.
If this keeps happening, please open an issue..
```
### Logs  
```
Step 4/19 : WORKDIR /src
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in df2b58e498c6
Removing intermediate container df2b58e498c6
 ---> 10239175923d
Step 5/19 : COPY go.mod go.sum ./
failed to get destination image "sha256:10239175923db962ee079a992b989b5dbc02f75d9a93cd4489ecf15e9f27ec4d": image with reference sha256:10239175923db962ee079a992b989b5dbc02f75d9a93cd4489ecf15e9f27ec4d was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64
```

### Screenshots 
<img width="1434" alt="Screen Shot 2023-01-16 at 2 13 51 PM" src="https://user-images.githubusercontent.com/18252105/212760414-0d1b8964-358f-49ea-bed2-099b5faa1e7e.png">

### Environment 
MacOS Monterey v12.6
Kubernetes distribution: Minikube v1.28.0
Docker Desktop for Apple Silicon v20.10.22

### Additional context 
How to configure this `microservice-demo` to run on Apple silicon M2?

**Comment by shazibulislam** [comment] 2023-01-16 22:30
@NimJay can you please help?

**Comment by NimJay** [comment] 2023-01-17 15:45
Thanks for reporting this clear and thorough GitHub issue, @shazibulislam.

Unfortunately, today, we don't support the deployment (or development) of Online Boutique on ARM-based devices — out of the box.
But **supporting ARM is a definitely a goal of ours in 2023**.

In the meantime, the [discussion inside issue 622](https://github.com/GoogleCloudPlatform/microservices-demo/issues/622#issuecomment-1336770586) might help you make slight changes to Online Boutique's `skaffold.yaml`, `Dockerfile`s, and other files such that `skaffold run` works on your M1 chip (ARM-based) machine.

I will keep this GitHub issue open until Online Boutique supports development (`skaffold dev` and `skaffold run`) on ARM-based devices.

**Comment by NimJay** [comment] 2023-04-18 18:24
**Update:** We have not made additional progress on this.

**Comment by minherz** [comment] 2023-07-26 22:17
Reframing this issue as "feature request". We will assess the expectations to support Mac platform for building the project. Please,  vote for this feature using :+1:  and :-1:  **in the description**

**Comment by woop** [comment] 2023-08-10 22:08
These changes worked for me an an ARM M1 Mac https://github.com/woop/microservices-demo/commit/62b5938b59447b4fb57263d0b71f009ba43c1494

**Comment by roisec** [comment] 2024-02-29 14:04
@NimJay 
Any progress with this issue?

**Comment by bourgeoisor** [comment] 2024-04-17 22:12
Closing as a duplicate of https://github.com/GoogleCloudPlatform/microservices-demo/issues/622

**Closed by bourgeoisor** 2024-04-17 22:12 UTC
Labels: type: feature request, priority: p3
