### ISSUE TITLE
CurrencyService and PaymentService failing on skaffold run

### ISSUE THREAD

**Issue by VictorNM** [GoogleCloudPlatform/microservices-demo#619] opened 2021-11-11 08:42 UTC
Running `skaffold run` on branch `master` and `v0.3.0` produce error when build CurrencyService and PaymentService like below:

```console
Building [currencyservice]...
Sending build context to Docker daemon  162.3kB
Step 1/13 : FROM node:12-alpine as base
 ---> f534e2bb4a44
Step 2/13 : FROM base as builder
 ---> f534e2bb4a44
Step 3/13 : RUN apk add --update --no-cache     python     make     g++
 ---> Running in f458b16b79c2
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  python (no such package):
    required by: world[python]
```

```console
Building [paymentservice]...
Sending build context to Docker daemon  154.1kB
Step 1/13 : FROM node:12-alpine as base
 ---> f534e2bb4a44
Step 2/13 : FROM base as builder
 ---> f534e2bb4a44
Step 3/13 : RUN apk add --update --no-cache     python     make     g++
 ---> Running in e6f4fe59a245
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  python (no such package):
    required by: world[python]
```

Seem like this change in currencyservice/Dockerfile and paymentservice/Dockerfile will fix the error
From:
```Dockerfile
RUN apk add --update --no-cache \
    python \
    make \
    g++ 
```

To:
```Dockerfile
RUN apk add --update --no-cache \
    py-pip \
    make \
    g++ 
```

**Comment by ckim328** [comment] 2021-11-11 15:40
Hi! Could you give us more info on your environment? (Docker version, OS)

**Comment by NimJay** [comment] 2021-11-11 16:09
@ckim328 and I were able to reproduce this issue — so we no longer need the environment details! :)
Thanks so much for reporting this issue and suggesting a solution, @VictorNM!
I'll be working on a PR sometime today.

**Comment by NimJay** [comment] 2021-11-11 17:07
It looks like this issue is identical to https://github.com/GoogleCloudPlatform/microservices-demo/pull/616.

**Comment by julianwagle** [comment] 2021-11-11 18:44
> It looks like this issue is identical to #616.

Yes, same issue! Interesting solution put forward here. Does anyone know the benefits of using py-pip as opposed to python2? If there are known benefits, I would be more than happy to change my push request.

**Comment by NimJay** [comment] 2021-11-11 21:01
Hi @julianwagle!
First, thanks so much for creating #616!
Your PR (along with Victor's fix) inspired us the create #621 — which just uses `python3`.
@ckim328 and I decided on `python3` — since `python2` is [no longer maintained](https://www.python.org/doc/sunset-python-2/). But we're not Python experts. 🤷‍♂️  And it's unclear if `python` is even needed in this Dockerfile anymore.
If you update #616 to match  #621 (i.e., use 3 instead of 2), I'm more than happy to merge #616 — but no pressure. :)

**Comment by julianwagle** [comment] 2021-11-11 21:27
Sounds like a great idea! Thanks for reaching out with the above response. I went ahead and edited #616 - a merge would be appreciated if it's not a burden. Thanks again!

**Comment by NimJay** [comment] 2021-11-12 13:22
Fixed in https://github.com/GoogleCloudPlatform/microservices-demo/issues/619. Closing this issue. Thanks, all!

**Closed by NimJay** 2021-11-12 13:22 UTC
Labels: type: bug, priority: p1
